import Head from 'next/head'
import Contacts from '../ui/contacts';
// import Movies from '../ui/Home/Movies';
// import SearchInput from '../ui/Home/SearchInput';

export default function Home({projectTypes}) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        {/* <SearchInput /> */}
        {/* <Movies /> */}
        <Contacts projectTypes={projectTypes}/> 
      </main>
    </>
  )
}

export async function getStaticProps() {
  // Instead of fetching your `/api` route you can call the same
  // function directly in `getStaticProps`
  // const posts = await loadPosts()
  const projectTypes = ["Villa", "Residential", "Office", "Other"];

  // Props returned will be passed to the page component
  return {
    props: {projectTypes},
  }
}